# entryPoints:
  # web:
  #   address: ":80"
  # http:
  #   redirections:
  #     entryPoint:
  #       to: "websecure"
  #       scheme: "https"

http:
  routers:
    backend:
      rule: "Host(`localhost`)" 
      service: backend
      entryPoints:
        - web #websecure
      # tls: true
    test:
      rule: "Host(`test.localhost`)" 
      service: test
      entryPoints:
        - web #websecure

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://backend:80"
    test:
      loadBalancer:
        servers:
          - url: "http://backend:10008"

