services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 8080:80
    depends_on:
      - mysql

  traefik:
    image: traefik:latest
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --entrypoints.web.address=:80

      - --log.level=DEBUG
      - --providers.http.endpoint=http://backend/api/traefikconfig
      - --providers.http.pollInterval=10s #60s
    ports:
      - 88:80
      - 8081:8080
      #   - 443:443s

  rasp1:
    build:
      context: ./raspberry
    volumes:
      - ./raspberry/raspberry_local_ports:/etc/airnet/ports
      - ./raspberry/register.sh:/register.sh
      - ./raspberry/nginx.conf:/etc/nginx/nginx.conf
      - ./raspberry/entrypoint.sh:/entrypoint.sh
      - ./raspberry/index.html:/var/www/http2/index.html
    depends_on:
      - backend
    entrypoint: ["/entrypoint.sh"]

volumes:
  db-data:
