services:
    backend:
        image: node:latest
        working_dir: /app
        volumes:
            - ./backend:/app
            # - /app/node_modules #Ignore node modules
        depends_on:
            - mysql
        ports:
            - 80:80
        command: "npx ts-node-dev --respawn --transpile-only --poll index.js"

    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        ports:
            - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${DATABASE_ROOT_PASSWORD}"]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - db-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        ports:
            - 8080:80
        depends_on:
            - mysql

    rasp1:
        volumes:
            - ./raspberry/raspberry_local_ports:/etc/airnet/ports
            - ./raspberry/register.sh:/workspace/register.sh
            - ./raspberry/nginx.conf:/etc/nginx/nginx.conf
        build:
            dockerfile: ./raspberry/Dockerfile
        depends_on:
            - backend

volumes:
    db-data:
