# Raspberry image
FROM debian:stable-slim

RUN apt-get update && \
    apt-get install -y lsof && \
    apt-get install -y curl

WORKDIR /workspace
EXPOSE 80
COPY ./register.sh /workspace/

CMD ["/workspace/register.sh"]
