# Raspberry image
FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y systemd && \
    apt-get install -y lsof

WORKDIR /workspace
EXPOSE 80
COPY ./register.sh /workspace/

CMD ["/workspace/register.sh"]