services:
    backend:
        build:
            context: ./backend
        volumes:
            - ./backend:/app
        depends_on:
            - mysql
        ports:
            - 80:80
        # healthcheck:
        #     test: curl -f http://localhost/api/health
        #     interval: 20s
        #     timeout: 10s
        #     retries: 5

    mysql:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        ports:
            - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${DATABASE_ROOT_PASSWORD}"]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - db-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        ports:
            - 8080:80
        depends_on:
            - mysql

    traefik:
        image: traefik:latest
        # Enables the web UI and tells Traefik to listen to docker
        command: --api.insecure=true --providers.docker
        ports:
            # The HTTP port
            - "81:80"
            # The Web UI (enabled by --api.insecure=true)
            - "8081:8080"
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock
    rasp1:
        build:
            context: ./raspberry
        volumes:
            - ./raspberry/raspberry_local_ports:/etc/airnet/ports
            - ./raspberry/register.sh:/register.sh
            - ./raspberry/nginx.conf:/etc/nginx/nginx.conf
            - ./raspberry/entrypoint.sh:/entrypoint.sh
        depends_on:
            - backend
        entrypoint: ["/entrypoint.sh"]

volumes:
    db-data:
